server:
  port: 2333

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:-youshallnotpass}
    sources:
      youtube: true
      http: true
      local: false
      soundcloud: false
      bandcamp: false
      twitch: false
      vimeo: false
      nico: false

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.14.0"
    repository: "https://maven.lavalink.dev/releases"
  - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.4.2"
    repository: "https://maven.topi.wtf/releases"

lavasrc:
  sources:
    spotify: true
  providers:
    - "spsearch"
    - "ytsearch"
  spotify:
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}
